# MAINTENANCE NOTES
# -----------------
#
# * Any backwards incompatible inputs require a major version change.
# * Ordinarily for the same major+minor `dk-version` that cache should be compatible across patch versions.
#   But if a dk0 patch release accidentally corrupts a cache, search/replace and bump "-x1" to evict
#   _every_ user cache AND put a note in the release notes AND put a
#   "⚠️ warning: cache evicted administratively" as a GitHub step for at least a week. You might make
#   that easier for users by using a `if:` on the cache to use a bump (ex. "-x1" -> "-x2") only for
#   the affected major+minor `dk-version`
name: 'Combine dk modules'
description: 'Combine one or more dk modules into a single distribution'
branding:
  icon: cloud-lightning
  color: 'gray-dark'
inputs:
  dk-version:
    description: 'The version of the dk build system to use. The default is the latest version.'
    required: false
    default: '2.5'
  id:
    description: 'The library and version of your distribution. Defaults to github repository (without the owner) plus @ plus the github reference (ie. tag or branch). Ex. CommonsBase_Std@1.0.1. The version must be valid semver. Any semver build metadata (a "+" and [0-9A-Za-z-] characters) is stripped.'
    required: false # true does nothing
  options:
    description: 'Options to pass to `dk` and/or `dk0`.'
    required: false
  experimental-dk-owner:
    description: "The 'dk' repository owner's username. The GitHub repository would then be github.com/<owner>/dk.git. Defaults to 'diskuv'. Do not use for production."
    required: false
    default: 'diskuv'
  experimental-mlfront-ref:
    description: 'Use the bleeding edge of https://gitlab.com/dkml/build-tools/MlFront.git. Do not use for production.'
    required: false
    default: 'false'
  execution-abi:
    description: 'Set the execution_abi wildcard so executables (compilers, etc.) are selected that run on the ABI.'
    required: false
  target-abi:
    description: 'Set the target_abi wildcard so executables and libraries are generated for the ABI.'
    required: false
runs:
  using: composite
  steps:
      - name: Check Runner OS
        if: runner.os != 'Linux' && runner.os != 'Windows' && runner.os != 'macOS'
        shell: bash
        run: |
          echo "::error title=⛔ error hint::Support Linux, Windows, and macOS Only"
          exit 1

      - name: Set dk-distribute/combine variables
        id: dk-vars
        shell: bash
        env:
          INPUTVERSION: ${{ inputs.dk-version }}
          INPUTID: ${{ inputs.id }}
        run: |
          case "${{ env.INPUTVERSION }}" in
            2.4) DK_BUILD_VERSION_REF=V2_4; DK_BUILD_VERSION_MAJMIN=2.4 ;;
            2.5) DK_BUILD_VERSION_REF=V2_5; DK_BUILD_VERSION_MAJMIN=2.5 ;;
            *) echo "::error title=⛔ error hint::Unsupported version '${{ env.INPUTVERSION }}'. Supported versions: 2.4, 2.5"; exit 1 ;;
          esac
          echo "dk_build_version_ref=${DK_BUILD_VERSION_REF}" | tee -a "$GITHUB_OUTPUT"

          # default 'id' will be github.repository + '@' + github.ref_name except
          # github.repository (owner/repo) will not have the "owner/" prefix.
          # ex. 'repo@1.2.3'
          DK_ID='${{ env.INPUTID }}'
          if [ -z "$DK_ID" ]; then
            DK_ID_REPOSITORY="${{ github.repository }}"
            DK_ID="${DK_ID_REPOSITORY#*/}@${{ github.ref_name }}"
          fi

          # split id into library_id and version
          if [[ "$DK_ID}" != *@* ]]; then
            echo "::error title=⛔ error hint::Invalid id '${{ env.INPUTID }}'. Must be of the form SomeLibrary_Unit@Version, like CommonsBase_Std@1.0.1"
            exit 1
          fi
          DK_ID_LIBRARY="${DK_ID%@*}"
          DK_ID_VERSION="${DK_ID#*@}"
          if [[ -z "$DK_ID_LIBRARY" || -z "$DK_ID_VERSION" ]]; then
            echo "::error title=⛔ error hint::Invalid id '${{ env.INPUTID }}'. Must be of the form SomeLibrary_Unit@Version, like CommonsBase_Std@1.0.1"
            exit 1
          fi

          echo "dk_id_library=${DK_ID_LIBRARY}" | tee -a "$GITHUB_OUTPUT"

      # --------- Linux static toolchain ----------

      - name: Prepare Linux static toolchain
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        env:
          INPUTDISTSCRIPT: ${{ inputs.distscript }}
          TARGET_ABI: ${{ inputs.target-abi || inputs.execution-abi }}
        run: |
          if command -v dnf > /dev/null 2>&1; then
            pkgs=(glibc-static)
            case "${{ env.INPUTDISTSCRIPT }},${{ env.TARGET_ABI }}" in
              dist-Linux_x86_64.u,*) ;;
              dist-Linux_arm64.u,*) ;;
              dist-Linux_armv7.u,*) ;;
              *,Linux_x86_64) ;;
              *,Linux_arm64) ;;
              dist-Linux_x86.u,*|*,Linux_x86)
                pkgs+=(glibc-static.i686 glibc-devel.i686 libgcc.i686 libstdc++.i686 gcc-toolset-14-libstdc++-devel.i686)
                ;;
              *) echo "::error title=⛔ error hint::Unsupported distribution script '${{ env.INPUTDISTSCRIPT }}' for Linux. Linux distribution scripts 'dist-Linux_x86_64.u', 'dist-Linux_arm64.u', 'dist-Linux_armv7.u' or 'dist-Linux_x86.u' or Linux execution-abi 'Linux_x86_64', 'Linux_arm64' or 'Linux_x86' supported."; exit 1 ;;
            esac
            dnf install -y "${pkgs[@]}"
          fi

      # --------- C.1: Get dksrc/dk0 ----------

      - name: Get dksrc/dk0
        if: >
          inputs.experimental-dk-owner != ''
          && (inputs.experimental-mlfront-ref == '' || inputs.experimental-mlfront-ref == 'false')
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.experimental-dk-owner }}/dk
          path: dksrc
          ref: ${{ steps.dk-vars.outputs.dk_build_version_ref }}

      - name: Get dksrc/dk0
        if: >
          inputs.experimental-dk-owner == ''
          && (inputs.experimental-mlfront-ref == '' || inputs.experimental-mlfront-ref == 'false')
        uses: actions/checkout@v6
        with:
          repository: diskuv/dk
          path: dksrc
          ref: ${{ steps.dk-vars.outputs.dk_build_version_ref }}

      # --------- C.2: Install dksrc/dk0 ----------
      - name: Check if bwrap available for sandboxing
        id: check-bwrap
        if: inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: bash
        # opam sandboxing means bubblewrap must be on Linux runners, but the manylinux images which
        # provide old glibc versions do not have bubblewrap.
        # So make the availability of bwrap be a variable for the next "Set-up OCaml" step.
        run: |
          if [ "${{ runner.os }}" != "Linux" ]; then
            echo "Non-Linux OS detected, skipping bwrap check."
            echo "disable_sandboxing=false" | tee -a "$GITHUB_OUTPUT"
            exit 0
          fi
          if command -v bwrap > /dev/null 2>&1; then
            echo "bwrap is available for sandboxing"
            echo "disable_sandboxing=false" | tee -a "$GITHUB_OUTPUT"
          else
            echo "bwrap is not available."
            echo "disable_sandboxing=true" | tee -a "$GITHUB_OUTPUT"
          fi
      - name: Set-up OCaml
        if: inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        uses: ocaml/setup-ocaml@57d9aa353e8d39677b1b9fc39637d48f27fe4a91 # v3
        with:
          ocaml-compiler: 5.4.0
          opam-disable-sandboxing: ${{ steps.check-bwrap.outputs.disable_sandboxing == 'true' }}
          #   (synced from OCAML_OPAM_REPOSITORY in MlFront/.gitlab-ci.yml)
          #   2025-12-18. fmlib_parse.0.6.2
          #   2025-11-08. dkml-c-probe.3.2.0
          #   2025-10-10. initial
          opam-repositories: |
            default: git+https://github.com/ocaml/opam-repository.git#93d44806c4a413399879355cb22fb53ba00a1ba5
          cache-prefix: dk-distribute-v2
      - name: Get MlFront
        if: inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: bash
        #   `git commit` required since `opam pin`` uses git+file://
        run: |
          git clone https://gitlab.com/dkml/build-tools/MlFront.git
          cd MlFront
          git reset --hard '${{ inputs.experimental-mlfront-ref }}'

          sh ci/localize-pristine.sh
          git config user.email "nobody@example.com"
          git config user.name "nobody"
          git add --force dune-project *.opam
          git commit -m "pristine"

          printf 'opam version: '
          opam --version
      - name: Pin Latest MlFront
        if: inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: bash
        run: cd MlFront && opam pin . --no-action -y
      - name: Install DkZero_Exec
        if: inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: bash
        # Use `./DkZero_Exec.opam` not `DkZero_Exec` to process pin-depends:[]
        run: cd MlFront && opam install ./DkZero_Exec.opam -y
      - name: Create dksrc/dk0 Wrapper on Unix
        if: runner.os != 'Windows' && inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: bash
        run: |
          install -d dksrc
          printf '#!/bin/sh\nset -euf\nopam exec -- dk0 "$@"\n' | tee dksrc/dk0
          chmod +x dksrc/dk0
      - name: Create dksrc\dk0.cmd Wrapper on Windows
        if: runner.os == 'Windows' && inputs.experimental-mlfront-ref != '' && inputs.experimental-mlfront-ref != 'false'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path dksrc -Force | Out-Null
          $content = "@echo off`nsetlocal enabledelayedexpansion`nopam exec -- dk0 %*`n"
          Set-Content -Path dksrc\dk0.cmd -Value $content -Encoding ASCII

      # --------- D.1 Download ----------

      - name: Download distribution artifacts
        uses: actions/download-artifact@v8
        with:
          path: dk-dist
          pattern: distribution-*
          merge-multiple: true

      # --------- G.1 Distribute ----------

      - name: Combine on Unix
        env:
          INPUTOPTIONS: >-
            ${{ inputs.options }}
            ${{ inputs.execution-abi && format('--execution-abi {0}', inputs.execution-abi) }}
            ${{ inputs.target-abi && format('--target-abi {0}', inputs.target-abi) }}
        shell: bash
        if: runner.os != 'Windows'
        # --errors-plain option helps cross-platform CI caches since the cache+data is under the project t/ subdirectory
        run: |
          echo "dksrc/dk0 --errors-plain ${{ env.INPUTOPTIONS }} --verbose combine --origin-name '${{ steps.dk-vars.outputs.dk_id_library }}' --mirror '${{github.server_url}}/${{github.repository}}/releases/download/${{github.ref_name}}'"
          dksrc/dk0 --errors-plain ${{ env.INPUTOPTIONS }} --verbose combine --origin-name '${{ steps.dk-vars.outputs.dk_id_library }}' --mirror '${{github.server_url}}/${{github.repository}}/releases/download/${{github.ref_name}}'

          du -sh dk-dist/*

      - name: Combine on Windows
        env:
          INPUTOPTIONS: >-
            ${{ inputs.options }}
            ${{ inputs.execution-abi && format('--execution-abi {0}', inputs.execution-abi) }}
            ${{ inputs.target-abi && format('--target-abi {0}', inputs.target-abi) }}
        shell: pwsh
        if: runner.os == 'Windows'
        run: |
          Write-Host "dksrc\dk0.cmd --errors-plain ${{ env.INPUTOPTIONS }} --verbose combine --origin-name '${{ steps.dk-vars.outputs.dk_id_library }}' --mirror '${{github.server_url}}/${{github.repository}}/releases/download/${{github.ref_name}}'"
          dksrc\dk0.cmd --errors-plain ${{ env.INPUTOPTIONS }} --verbose combine --origin-name '${{ steps.dk-vars.outputs.dk_id_library }}' --mirror '${{github.server_url}}/${{github.repository}}/releases/download/${{github.ref_name}}'
          if ($LASTEXITCODE -ne 0) {
            throw "dk0 combine failed with exit code $LASTEXITCODE"
          }

          Get-ChildItem -Directory dk-dist | ForEach-Object {
              $size = (Get-ChildItem $_.FullName -Recurse -File | Measure-Object -Property Length -Sum).Sum
              $sizeGB = [math]::Round($size / 1GB, 2)
              Write-Output "$($sizeGB) GB`t$($_.Name)"
          }

      - name: Document Import Command
        shell: bash
        run: |
          # parse options
          tag='${{ github.ref_name }}'
          repository='${{ github.repository }}'
          capture() {
            printf "%s\n" "$@" >> "$GITHUB_STEP_SUMMARY"
            printf "%s\n" "$@" >> '.dist-CHANGELOG.txt'
          }
          if [ -z "$repository" ]; then
            echo "Error: repository is required" >&2
            usage
          fi
          if [ -z "$tag" ]; then
            echo "Error: tag is required" >&2
            usage
          fi

          capture "### Importing this package version"
          capture ''
          capture '```'

          printf "./dk0 add github-l2 %s@%s\n" "$repository" "$tag"
          capture "./dk0 add github-l2 ${repository}@${tag}"
          capture '```'

          capture ''
          capture "### Importing the latest package version"
          capture ''
          capture '```'

          printf "./dk0 add github-l2 %s\n" "$repository"
          capture "./dk0 add github-l2 ${repository}"
          capture '```'
